# Generated by Django 4.0.4 on 2022-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('amount', models.IntegerField()),
                ('spent_at', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(max_length=15)),
            ],
        ),
    ]
